### ISSUE TITLE
Log file?

### ISSUE THREAD

**Issue by n0brainer** [trice81384/macOSSoftwareUpdates#4]
I was wondering if there was a location that I could look at for logging to help ensure things are working as expected.  I did a keyword search for log, but didn't see any lines in the script specifically calling it out, but it could just be the keyword search I used.

**Comment by tom-electric** [comment]
@n0brainer The script itself does not do any advanced logging other that what functions are running when as well as what the amount of remaining deferrals are, the user logged it, etc. You can search the script for echo commands to see most of them as they are designed to be outputted to the results of a jamf policy. Any logging done by built in binaries (such as the softwareupdate binary) is handled by macOS' built in logging.

**Comment by trice81384** [comment]
@n0brainer  The script itself does not do any advanced logging other that what functions are running when as well as what the amount of remaining deferrals are, the user logged it, etc. You can search the script for echo commands to see most of them as they are designed to be outputted to the results of a jamf policy. Any logging done by built in binaries (such as the softwareupdate binary) is handled by macOS' built in logging.
